// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ninexhype.Data;

#nullable disable

namespace ninexhype.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "bec71b05-8f3d-4849-88bb-0e8d518d2de8",
                            Name = "Funcionário",
                            NormalizedName = "FUNCIONÁRIO"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("perfil_regra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_regra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuario_perfil", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            UserId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            RoleId = "bec71b05-8f3d-4849-88bb-0e8d518d2de8"
                        },
                        new
                        {
                            UserId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            RoleId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuario_token", (string)null);
                });

            modelBuilder.Entity("ninexhype.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TipoRoupaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoRoupaId");

                    b.ToTable("categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tênis",
                            TipoRoupaId = 2
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Camisas",
                            TipoRoupaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Blusas",
                            TipoRoupaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Jaquetas",
                            TipoRoupaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Shorts",
                            TipoRoupaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Calças",
                            TipoRoupaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Acessórios",
                            TipoRoupaId = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Destaques",
                            TipoRoupaId = 1
                        });
                });

            modelBuilder.Entity("ninexhype.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AtividadeRecomendada")
                        .HasColumnType("longtext");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Material")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("QtdeEstoque")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Branco",
                            Descricao = "Tênis casual branco clássico",
                            Destaque = false,
                            Genero = 3,
                            Marca = "Nike",
                            Material = "Couro",
                            Nome = "Nike Air Force 1",
                            QtdeEstoque = 25,
                            ValorCusto = 300.00m,
                            ValorVenda = 449.99m
                        },
                        new
                        {
                            Id = 2,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 1,
                            Cor = "Preto",
                            Descricao = "Tênis esportivo com amortecimento",
                            Destaque = false,
                            Genero = 3,
                            Marca = "Adidas",
                            Material = "Tecido Knit",
                            Nome = "Adidas Ultraboost",
                            QtdeEstoque = 18,
                            ValorCusto = 380.00m,
                            ValorVenda = 599.99m
                        },
                        new
                        {
                            Id = 3,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Colorido",
                            Descricao = "Tênis estiloso retrô",
                            Destaque = false,
                            Genero = 1,
                            Marca = "Puma",
                            Material = "Tecido e Sintético",
                            Nome = "Puma RS-X",
                            QtdeEstoque = 20,
                            ValorCusto = 320.00m,
                            ValorVenda = 489.90m
                        },
                        new
                        {
                            Id = 4,
                            AtividadeRecomendada = "Skate",
                            CategoriaId = 1,
                            Cor = "Preto",
                            Descricao = "Tênis skatista em lona e camurça",
                            Destaque = false,
                            Genero = 1,
                            Marca = "Vans",
                            Material = "Lona e Camurça",
                            Nome = "Vans Old Skool",
                            QtdeEstoque = 22,
                            ValorCusto = 200.00m,
                            ValorVenda = 349.99m
                        },
                        new
                        {
                            Id = 5,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Cinza",
                            Descricao = "Tênis retrô confortável",
                            Destaque = false,
                            Genero = 3,
                            Marca = "New Balance",
                            Material = "Suede e Malha",
                            Nome = "New Balance 574",
                            QtdeEstoque = 15,
                            ValorCusto = 280.00m,
                            ValorVenda = 419.99m
                        },
                        new
                        {
                            Id = 6,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Preto",
                            Descricao = "Tênis cano alto icônico",
                            Destaque = false,
                            Genero = 3,
                            Marca = "Converse",
                            Material = "Lona",
                            Nome = "Converse Chuck Taylor",
                            QtdeEstoque = 30,
                            ValorCusto = 150.00m,
                            ValorVenda = 269.99m
                        },
                        new
                        {
                            Id = 7,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 1,
                            Cor = "Azul",
                            Descricao = "Tênis de corrida com suporte",
                            Destaque = false,
                            Genero = 3,
                            Marca = "Asics",
                            Material = "Mesh",
                            Nome = "Asics Gel-Kayano 28",
                            QtdeEstoque = 12,
                            ValorCusto = 400.00m,
                            ValorVenda = 649.99m
                        },
                        new
                        {
                            Id = 8,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Colorido",
                            Descricao = "Tênis streetwear com cores vibrantes",
                            Destaque = false,
                            Genero = 3,
                            Marca = "Nike",
                            Material = "Couro e Sintético",
                            Nome = "Nike Dunk Low",
                            QtdeEstoque = 10,
                            ValorCusto = 360.00m,
                            ValorVenda = 549.99m
                        },
                        new
                        {
                            Id = 9,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 1,
                            Cor = "Preto",
                            Descricao = "Tênis de performance com amortecimento",
                            Destaque = false,
                            Genero = 1,
                            Marca = "Mizuno",
                            Material = "Mesh e Borracha",
                            Nome = "Mizuno Wave Prophecy",
                            QtdeEstoque = 8,
                            ValorCusto = 500.00m,
                            ValorVenda = 799.99m
                        },
                        new
                        {
                            Id = 10,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Branco",
                            Descricao = "Tênis chunky retrô",
                            Destaque = false,
                            Genero = 2,
                            Marca = "Fila",
                            Material = "Sintético",
                            Nome = "Fila Disruptor II",
                            QtdeEstoque = 14,
                            ValorCusto = 220.00m,
                            ValorVenda = 369.99m
                        },
                        new
                        {
                            Id = 11,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Branco",
                            Descricao = "Tênis casual vintage",
                            Destaque = false,
                            Genero = 3,
                            Marca = "Reebok",
                            Material = "Couro",
                            Nome = "Reebok Classic",
                            QtdeEstoque = 16,
                            ValorCusto = 180.00m,
                            ValorVenda = 299.99m
                        },
                        new
                        {
                            Id = 12,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 1,
                            Cor = "Preto",
                            Descricao = "Tênis esportivo respirável",
                            Destaque = false,
                            Genero = 1,
                            Marca = "Under Armour",
                            Material = "Tecido Knit",
                            Nome = "Under Armour HOVR",
                            QtdeEstoque = 10,
                            ValorCusto = 310.00m,
                            ValorVenda = 459.99m
                        },
                        new
                        {
                            Id = 13,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 1,
                            Cor = "Preto/Vermelho",
                            Descricao = "Tênis icônico da linha Jordan",
                            Destaque = false,
                            Genero = 1,
                            Marca = "Nike Jordan",
                            Material = "Couro",
                            Nome = "Jordan 1 Mid",
                            QtdeEstoque = 6,
                            ValorCusto = 450.00m,
                            ValorVenda = 749.99m
                        },
                        new
                        {
                            Id = 14,
                            AtividadeRecomendada = "Trilha",
                            CategoriaId = 1,
                            Cor = "Marrom",
                            Descricao = "Tênis robusto e confortável",
                            Destaque = false,
                            Genero = 1,
                            Marca = "Oakley",
                            Material = "Couro e Borracha",
                            Nome = "Oakley Modoc",
                            QtdeEstoque = 18,
                            ValorCusto = 280.00m,
                            ValorVenda = 399.99m
                        },
                        new
                        {
                            Id = 15,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 1,
                            Cor = "Branco/Verde",
                            Descricao = "Tênis de corrida profissional",
                            Destaque = false,
                            Genero = 1,
                            Marca = "Nike",
                            Material = "Mesh",
                            Nome = "Nike ZoomX Vaporfly",
                            QtdeEstoque = 5,
                            ValorCusto = 600.00m,
                            ValorVenda = 999.99m
                        },
                        new
                        {
                            Id = 16,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 2,
                            Cor = "Branco",
                            Descricao = "100% algodão, modelagem larga",
                            Destaque = false,
                            Genero = 1,
                            Marca = "9xHype",
                            Material = "Algodão",
                            Nome = "Camiseta Oversized Branca",
                            QtdeEstoque = 50,
                            ValorCusto = 40.00m,
                            ValorVenda = 79.90m
                        },
                        new
                        {
                            Id = 17,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 6,
                            Cor = "Preto",
                            Descricao = "Com bolsos laterais e ajuste no tornozelo",
                            Destaque = false,
                            Genero = 1,
                            Marca = "9xHype",
                            Material = "Algodão e Poliéster",
                            Nome = "Calça Cargo Preta",
                            QtdeEstoque = 30,
                            ValorCusto = 90.00m,
                            ValorVenda = 149.99m
                        },
                        new
                        {
                            Id = 18,
                            AtividadeRecomendada = "Esportivo",
                            CategoriaId = 4,
                            Cor = "Cinza",
                            Descricao = "Impermeável e leve, ideal para dias chuvosos",
                            Destaque = false,
                            Genero = 3,
                            Marca = "9xHype",
                            Material = "Poliéster",
                            Nome = "Jaqueta Corta-Vento",
                            QtdeEstoque = 12,
                            ValorCusto = 120.00m,
                            ValorVenda = 219.99m
                        },
                        new
                        {
                            Id = 19,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 3,
                            Cor = "Cinza",
                            Descricao = "Moletom peluciado unissex",
                            Destaque = false,
                            Genero = 3,
                            Marca = "9xHype",
                            Material = "Algodão",
                            Nome = "Moletom Liso com Capuz",
                            QtdeEstoque = 25,
                            ValorCusto = 80.00m,
                            ValorVenda = 129.90m
                        },
                        new
                        {
                            Id = 20,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 5,
                            Cor = "Bege",
                            Descricao = "Estilo casual, com bolsos laterais",
                            Destaque = false,
                            Genero = 1,
                            Marca = "9xHype",
                            Material = "Sarja",
                            Nome = "Bermuda de Sarja Bege",
                            QtdeEstoque = 35,
                            ValorCusto = 60.00m,
                            ValorVenda = 99.99m
                        },
                        new
                        {
                            Id = 21,
                            AtividadeRecomendada = "Social",
                            CategoriaId = 2,
                            Cor = "Branca",
                            Descricao = "Camisa masculina, algodão, modelagem justa",
                            Destaque = false,
                            Genero = 1,
                            Marca = "9xHype",
                            Material = "Algodão",
                            Nome = "Camisa Social Slim",
                            QtdeEstoque = 20,
                            ValorCusto = 70.00m,
                            ValorVenda = 119.99m
                        },
                        new
                        {
                            Id = 22,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 2,
                            Cor = "Floral",
                            Descricao = "Vestido leve para o verão",
                            Destaque = false,
                            Genero = 2,
                            Marca = "9xHype",
                            Material = "Viscose",
                            Nome = "Vestido Midi Floral",
                            QtdeEstoque = 18,
                            ValorCusto = 90.00m,
                            ValorVenda = 149.90m
                        },
                        new
                        {
                            Id = 23,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 6,
                            Cor = "Azul Jeans",
                            Descricao = "Jeans com elastano para conforto",
                            Destaque = false,
                            Genero = 3,
                            Marca = "9xHype",
                            Material = "Jeans com Elastano",
                            Nome = "Calça Jeans Skinny",
                            QtdeEstoque = 28,
                            ValorCusto = 100.00m,
                            ValorVenda = 169.99m
                        },
                        new
                        {
                            Id = 24,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 4,
                            Cor = "Azul Jeans",
                            Descricao = "Estilo urbano e confortável",
                            Destaque = false,
                            Genero = 2,
                            Marca = "9xHype",
                            Material = "Jeans",
                            Nome = "Jaqueta Jeans Feminina",
                            QtdeEstoque = 10,
                            ValorCusto = 130.00m,
                            ValorVenda = 199.99m
                        },
                        new
                        {
                            Id = 25,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 5,
                            Cor = "Cinza",
                            Descricao = "Conforto para o dia a dia",
                            Destaque = false,
                            Genero = 3,
                            Marca = "9xHype",
                            Material = "Moletom",
                            Nome = "Shorts de Moletom",
                            QtdeEstoque = 40,
                            ValorCusto = 50.00m,
                            ValorVenda = 89.99m
                        },
                        new
                        {
                            Id = 26,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 2,
                            Cor = "Preto",
                            Descricao = "100% algodão, gola careca",
                            Destaque = false,
                            Genero = 2,
                            Marca = "9xHype",
                            Material = "Algodão",
                            Nome = "Camiseta Polo Preta Feminina",
                            QtdeEstoque = 60,
                            ValorCusto = 35.00m,
                            ValorVenda = 69.90m
                        },
                        new
                        {
                            Id = 27,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 2,
                            Cor = "Preto",
                            Descricao = "Look prático e estiloso",
                            Destaque = false,
                            Genero = 2,
                            Marca = "9xHype",
                            Material = "Viscose",
                            Nome = "Macacão Feminino",
                            QtdeEstoque = 14,
                            ValorCusto = 110.00m,
                            ValorVenda = 179.99m
                        },
                        new
                        {
                            Id = 28,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 3,
                            Cor = "Rosa",
                            Descricao = "Estilo jovem e leve",
                            Destaque = false,
                            Genero = 2,
                            Marca = "9xHype",
                            Material = "Poliéster",
                            Nome = "Blusa Cropped Texturizada",
                            QtdeEstoque = 22,
                            ValorCusto = 45.00m,
                            ValorVenda = 79.99m
                        },
                        new
                        {
                            Id = 29,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 2,
                            Cor = "Marrom",
                            Descricao = "Elegância casual",
                            Destaque = false,
                            Genero = 1,
                            Marca = "9xHype",
                            Material = "Algodão",
                            Nome = "Camisa Polo Texturizada Masculina Marrom",
                            QtdeEstoque = 19,
                            ValorCusto = 65.00m,
                            ValorVenda = 109.99m
                        },
                        new
                        {
                            Id = 30,
                            AtividadeRecomendada = "Treino",
                            CategoriaId = 2,
                            Cor = "Cinza",
                            Descricao = "Ideal para treinos",
                            Destaque = false,
                            Genero = 3,
                            Marca = "9xHype",
                            Material = "Poliéster",
                            Nome = "Regata Dry Fit",
                            QtdeEstoque = 50,
                            ValorCusto = 30.00m,
                            ValorVenda = 59.90m
                        },
                        new
                        {
                            Id = 31,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 8,
                            Cor = "Branco",
                            Descricao = "Tênis casual branco clássico",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Nike",
                            Material = "Couro",
                            Nome = "Nike Air Force 1",
                            QtdeEstoque = 25,
                            ValorCusto = 300.00m,
                            ValorVenda = 449.99m
                        },
                        new
                        {
                            Id = 32,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 8,
                            Cor = "Preto",
                            Descricao = "Tênis esportivo com amortecimento",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Adidas",
                            Material = "Tecido Knit",
                            Nome = "Adidas Ultraboost",
                            QtdeEstoque = 18,
                            ValorCusto = 380.00m,
                            ValorVenda = 599.99m
                        },
                        new
                        {
                            Id = 33,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 8,
                            Cor = "Colorido",
                            Descricao = "Tênis estiloso retrô",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Puma",
                            Material = "Tecido e Sintético",
                            Nome = "Puma RS-X",
                            QtdeEstoque = 20,
                            ValorCusto = 320.00m,
                            ValorVenda = 489.90m
                        },
                        new
                        {
                            Id = 34,
                            AtividadeRecomendada = "Skate",
                            CategoriaId = 8,
                            Cor = "Preto",
                            Descricao = "Tênis skatista em lona e camurça",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Vans",
                            Material = "Lona e Camurça",
                            Nome = "Vans Old Skool",
                            QtdeEstoque = 22,
                            ValorCusto = 200.00m,
                            ValorVenda = 349.99m
                        },
                        new
                        {
                            Id = 35,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 8,
                            Cor = "Cinza",
                            Descricao = "Tênis retrô confortável",
                            Destaque = false,
                            Genero = 0,
                            Marca = "New Balance",
                            Material = "Suede e Malha",
                            Nome = "New Balance 574",
                            QtdeEstoque = 15,
                            ValorCusto = 280.00m,
                            ValorVenda = 419.99m
                        },
                        new
                        {
                            Id = 36,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 8,
                            Cor = "Preto",
                            Descricao = "Tênis cano alto icônico",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Converse",
                            Material = "Lona",
                            Nome = "Converse Chuck Taylor",
                            QtdeEstoque = 30,
                            ValorCusto = 150.00m,
                            ValorVenda = 269.99m
                        },
                        new
                        {
                            Id = 37,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 8,
                            Cor = "Azul",
                            Descricao = "Tênis de corrida com suporte",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Asics",
                            Material = "Mesh",
                            Nome = "Asics Gel-Kayano 28",
                            QtdeEstoque = 12,
                            ValorCusto = 400.00m,
                            ValorVenda = 649.99m
                        },
                        new
                        {
                            Id = 38,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 8,
                            Cor = "Colorido",
                            Descricao = "Tênis streetwear com cores vibrantes",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Nike",
                            Material = "Couro e Sintético",
                            Nome = "Nike Dunk Low",
                            QtdeEstoque = 10,
                            ValorCusto = 360.00m,
                            ValorVenda = 549.99m
                        },
                        new
                        {
                            Id = 39,
                            AtividadeRecomendada = "Corrida",
                            CategoriaId = 8,
                            Cor = "Preto",
                            Descricao = "Tênis de performance com amortecimento",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Mizuno",
                            Material = "Mesh e Borracha",
                            Nome = "Mizuno Wave Prophecy",
                            QtdeEstoque = 8,
                            ValorCusto = 500.00m,
                            ValorVenda = 799.99m
                        },
                        new
                        {
                            Id = 40,
                            AtividadeRecomendada = "Casual",
                            CategoriaId = 8,
                            Cor = "Branco",
                            Descricao = "Tênis chunky retrô",
                            Destaque = false,
                            Genero = 0,
                            Marca = "Fila",
                            Material = "Sintético",
                            Nome = "Fila Disruptor II",
                            QtdeEstoque = 14,
                            ValorCusto = 220.00m,
                            ValorVenda = 369.99m
                        });
                });

            modelBuilder.Entity("ninexhype.Models.ProdutoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArquivoFoto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoFoto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArquivoFoto = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/AIR+FORCE+1+%2707.png",
                            ProdutoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArquivoFoto = "/img/500x500/AdidasUltraboost.png",
                            ProdutoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArquivoFoto = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/395984/02/sv01/fnd/PNA/fmt/png/RS-X-Retro-Resort-Women's-Sneakers",
                            ProdutoId = 3
                        },
                        new
                        {
                            Id = 4,
                            ArquivoFoto = "https://http2.mlstatic.com/D_NQ_NP_812678-MLB84265928797_052025-O.webp",
                            ProdutoId = 4
                        },
                        new
                        {
                            Id = 5,
                            ArquivoFoto = "https://nb.scene7.com/is/image/NB/wl574cor_nb_05_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
                            ProdutoId = 5
                        },
                        new
                        {
                            Id = 6,
                            ArquivoFoto = "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw187c312e/images/a_08/M7650_A_08X1.jpg?sw=406",
                            ProdutoId = 6
                        },
                        new
                        {
                            Id = 7,
                            ArquivoFoto = "https://images.asics.com/is/image/asics/1011B189_001_SR_RT_GLB?$sfcc-product$",
                            ProdutoId = 7
                        },
                        new
                        {
                            Id = 8,
                            ArquivoFoto = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d14fc386-1067-4a72-961e-9f8134680703/W+NIKE+DUNK+LOW.png",
                            ProdutoId = 8
                        },
                        new
                        {
                            Id = 9,
                            ArquivoFoto = "https://http2.mlstatic.com/D_NQ_NP_825783-MLA74802964877_022024-O.webp",
                            ProdutoId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArquivoFoto = "https://tse3.mm.bing.net/th/id/OIP.Edb0M5R6mDPgYzo4vrq3dQHaFS?rs=1&pid=ImgDetMain",
                            ProdutoId = 10
                        },
                        new
                        {
                            Id = 11,
                            ArquivoFoto = "https://tse3.mm.bing.net/th/id/OIP.Edb0M5R6mDPgYzo4vrq3dQHaFS?rs=1&pid=ImgDetMain",
                            ProdutoId = 10
                        },
                        new
                        {
                            Id = 12,
                            ArquivoFoto = "https://tse3.mm.bing.net/th/id/OIP.Edb0M5R6mDPgYzo4vrq3dQHaFS?rs=1&pid=ImgDetMain",
                            ProdutoId = 10
                        },
                        new
                        {
                            Id = 13,
                            ArquivoFoto = "/img/500x500/ReebokClassic1.png",
                            ProdutoId = 11
                        },
                        new
                        {
                            Id = 14,
                            ArquivoFoto = "/img/500x500/ReebokClassic2.png",
                            ProdutoId = 11
                        },
                        new
                        {
                            Id = 15,
                            ArquivoFoto = "/img/500x500/ReebokClassic3.png",
                            ProdutoId = 11
                        },
                        new
                        {
                            Id = 16,
                            ArquivoFoto = "/img/500x500/UnderArmourHOVR1.png",
                            ProdutoId = 12
                        },
                        new
                        {
                            Id = 17,
                            ArquivoFoto = "/img/500x500/UnderArmourHOVR2.png",
                            ProdutoId = 12
                        },
                        new
                        {
                            Id = 18,
                            ArquivoFoto = "/img/500x500/UnderArmourHOVR3.png",
                            ProdutoId = 12
                        },
                        new
                        {
                            Id = 19,
                            ArquivoFoto = "/img/500x500/Jordan1Mid1.png",
                            ProdutoId = 13
                        },
                        new
                        {
                            Id = 20,
                            ArquivoFoto = "/img/500x500/Jordan1Mid2.png",
                            ProdutoId = 13
                        },
                        new
                        {
                            Id = 21,
                            ArquivoFoto = "/img/500x500/Jordan1Mid3.png",
                            ProdutoId = 13
                        },
                        new
                        {
                            Id = 22,
                            ArquivoFoto = "/img/500x500/OakleyModoc1.png",
                            ProdutoId = 14
                        },
                        new
                        {
                            Id = 23,
                            ArquivoFoto = "/img/500x500/OakleyModoc2.png",
                            ProdutoId = 14
                        },
                        new
                        {
                            Id = 24,
                            ArquivoFoto = "/img/500x500/OakleyModoc3.png",
                            ProdutoId = 14
                        },
                        new
                        {
                            Id = 25,
                            ArquivoFoto = "/img/500x500/NikeZoomXVaporfly1.png",
                            ProdutoId = 15
                        },
                        new
                        {
                            Id = 26,
                            ArquivoFoto = "/img/500x500/NikeZoomXVaporfly2.png",
                            ProdutoId = 15
                        },
                        new
                        {
                            Id = 27,
                            ArquivoFoto = "/img/500x500/NikeZoomXVaporfly3.png",
                            ProdutoId = 15
                        },
                        new
                        {
                            Id = 28,
                            ArquivoFoto = "/img/500x500/CamisetaOversizedBranca1.png",
                            ProdutoId = 16
                        },
                        new
                        {
                            Id = 29,
                            ArquivoFoto = "/img/500x500/CamisetaOversizedBranca2.png",
                            ProdutoId = 16
                        },
                        new
                        {
                            Id = 30,
                            ArquivoFoto = "/img/500x500/CalcaCargoPreta1.png",
                            ProdutoId = 17
                        },
                        new
                        {
                            Id = 31,
                            ArquivoFoto = "/img/500x500/CalcaCargoPreta2.png",
                            ProdutoId = 17
                        },
                        new
                        {
                            Id = 32,
                            ArquivoFoto = "/img/500x500/CalcaCargoPreta3.png",
                            ProdutoId = 17
                        },
                        new
                        {
                            Id = 33,
                            ArquivoFoto = "/img/500x500/JaquetaCortaVento.png",
                            ProdutoId = 18
                        },
                        new
                        {
                            Id = 34,
                            ArquivoFoto = "/img/500x500/JaquetaCorta-Vento2.png",
                            ProdutoId = 18
                        },
                        new
                        {
                            Id = 35,
                            ArquivoFoto = "/img/500x500/JaquetaCorta-Vento3.png",
                            ProdutoId = 18
                        },
                        new
                        {
                            Id = 36,
                            ArquivoFoto = "/img/500x500/MoletomLisoCapuz1.png",
                            ProdutoId = 19
                        },
                        new
                        {
                            Id = 37,
                            ArquivoFoto = "/img/500x500/MoletomLisoCapuz2.png",
                            ProdutoId = 19
                        },
                        new
                        {
                            Id = 38,
                            ArquivoFoto = "/img/500x500/MoletomLisoCapuz3.png",
                            ProdutoId = 19
                        },
                        new
                        {
                            Id = 39,
                            ArquivoFoto = "/img/500x500/BermudaSarjaBege1.png",
                            ProdutoId = 20
                        },
                        new
                        {
                            Id = 40,
                            ArquivoFoto = "/img/500x500/BermudaSarjaBege1.png",
                            ProdutoId = 20
                        },
                        new
                        {
                            Id = 41,
                            ArquivoFoto = "/img/500x500/CamisaSocialSlim1.png",
                            ProdutoId = 21
                        },
                        new
                        {
                            Id = 42,
                            ArquivoFoto = "/img/500x500/CamisaSocialSlim2.png",
                            ProdutoId = 21
                        },
                        new
                        {
                            Id = 43,
                            ArquivoFoto = "/img/500x500/CamisaSocialSlim3.png",
                            ProdutoId = 21
                        },
                        new
                        {
                            Id = 44,
                            ArquivoFoto = "/img/500x500/VestidoMidiFloral1.png",
                            ProdutoId = 22
                        },
                        new
                        {
                            Id = 45,
                            ArquivoFoto = "/img/500x500/VestidoMidiFloral2.png",
                            ProdutoId = 22
                        },
                        new
                        {
                            Id = 46,
                            ArquivoFoto = "/img/500x500/VestidoMidiFloral3.png",
                            ProdutoId = 22
                        },
                        new
                        {
                            Id = 47,
                            ArquivoFoto = "/img/500x500/CalçaJeansSkinny1.png",
                            ProdutoId = 23
                        },
                        new
                        {
                            Id = 48,
                            ArquivoFoto = "/img/500x500/CalçaJeansSkinny2.png",
                            ProdutoId = 23
                        },
                        new
                        {
                            Id = 49,
                            ArquivoFoto = "/img/500x500/CalçaJeansSkinny3.png",
                            ProdutoId = 23
                        },
                        new
                        {
                            Id = 50,
                            ArquivoFoto = "/img/500x500/JaquetaJeansFeminina1.png",
                            ProdutoId = 24
                        },
                        new
                        {
                            Id = 51,
                            ArquivoFoto = "/img/500x500/JaquetaJeansFeminina2.png",
                            ProdutoId = 24
                        },
                        new
                        {
                            Id = 52,
                            ArquivoFoto = "/img/500x500/ShortsMoletom1.png",
                            ProdutoId = 25
                        },
                        new
                        {
                            Id = 53,
                            ArquivoFoto = "/img/500x500/ShortsMoletom2.png",
                            ProdutoId = 25
                        },
                        new
                        {
                            Id = 54,
                            ArquivoFoto = "/img/500x500/ShortsMoletom3.png",
                            ProdutoId = 25
                        },
                        new
                        {
                            Id = 55,
                            ArquivoFoto = "/img/500x500/CamisetaPoloPretaFeminina1.png",
                            ProdutoId = 26
                        },
                        new
                        {
                            Id = 56,
                            ArquivoFoto = "/img/500x500/CamisetaPoloPretaFeminina2.png",
                            ProdutoId = 26
                        },
                        new
                        {
                            Id = 57,
                            ArquivoFoto = "/img/500x500/MacacãoFeminino1.png",
                            ProdutoId = 27
                        },
                        new
                        {
                            Id = 58,
                            ArquivoFoto = "/img/500x500/MacacãoFeminino2.png",
                            ProdutoId = 27
                        },
                        new
                        {
                            Id = 59,
                            ArquivoFoto = "/img/500x500/MacacãoFeminino3.png",
                            ProdutoId = 27
                        },
                        new
                        {
                            Id = 60,
                            ArquivoFoto = "/img/500x500/BlusaCroppedTexturizada1.png",
                            ProdutoId = 28
                        },
                        new
                        {
                            Id = 61,
                            ArquivoFoto = "/img/500x500/BlusaCroppedTexturizada2.png",
                            ProdutoId = 28
                        },
                        new
                        {
                            Id = 62,
                            ArquivoFoto = "/img/500x500/BlusaCroppedTexturizada3.png",
                            ProdutoId = 28
                        },
                        new
                        {
                            Id = 63,
                            ArquivoFoto = "/img/500x500/CamisaPoloTexturizadaMasculinaMarrom1.png",
                            ProdutoId = 29
                        },
                        new
                        {
                            Id = 64,
                            ArquivoFoto = "/img/500x500/CamisaPoloTexturizadaMasculinaMarrom2.png",
                            ProdutoId = 29
                        },
                        new
                        {
                            Id = 65,
                            ArquivoFoto = "/img/500x500/RegataDryFit1.png",
                            ProdutoId = 30
                        },
                        new
                        {
                            Id = 66,
                            ArquivoFoto = "/img/500x500/RegataDryFit2.png",
                            ProdutoId = 30
                        },
                        new
                        {
                            Id = 97,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/NikeAirForce1.png",
                            ProdutoId = 31
                        },
                        new
                        {
                            Id = 98,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/AdidasUltraboost.png",
                            ProdutoId = 32
                        },
                        new
                        {
                            Id = 99,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/PumaRS-X.png",
                            ProdutoId = 33
                        },
                        new
                        {
                            Id = 100,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/VansOldSkool.png",
                            ProdutoId = 34
                        },
                        new
                        {
                            Id = 101,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/NewBalance574.png",
                            ProdutoId = 35
                        },
                        new
                        {
                            Id = 102,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/ConverseChuckTaylor.png",
                            ProdutoId = 36
                        },
                        new
                        {
                            Id = 103,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/AsicsGel-Kayano.png",
                            ProdutoId = 37
                        },
                        new
                        {
                            Id = 104,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/NikeDunkLow.png",
                            ProdutoId = 38
                        },
                        new
                        {
                            Id = 105,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/MizunoWaveProphecy.png",
                            ProdutoId = 39
                        },
                        new
                        {
                            Id = 106,
                            ArquivoFoto = "/img/FotosCarrossel/fotosGrandes/FilaDisruptorII.png",
                            ProdutoId = 40
                        });
                });

            modelBuilder.Entity("ninexhype.Models.TipoRoupa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tiporoupa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Roupa"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Tenis"
                        });
                });

            modelBuilder.Entity("ninexhype.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f39c33c6-9528-40c9-8e4c-13eb08537bee",
                            DataNascimento = new DateTime(1981, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gallojunior@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/ddf093a6-6cb5-4ff7-9a64-83da34aee005.png",
                            LockoutEnabled = true,
                            Nome = "José Antonio Gallo Junior",
                            NormalizedEmail = "GALLOJUNIOR@GMAIL.COM",
                            NormalizedUserName = "GALLOJUNIOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEPSQABJOUNMFiKeaRmUHzkATTgNNov+FrTQAIPk/r+06TV8xm/wKYuI2YW+JqrPWgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eaf63937-64ca-43e6-8d8b-51813ef76348",
                            TwoFactorEnabled = false,
                            UserName = "GalloJunior"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee006",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa4d8682-ad14-43f5-a29d-9a117a7a14e4",
                            DataNascimento = new DateTime(1981, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eduardo010304@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/ddf093a6-6cb5-4ff7-9a64-83da34aee005.png",
                            LockoutEnabled = true,
                            Nome = "Eduardo Ribeiro",
                            NormalizedEmail = "EDUARDO010304@GMAIL.COM",
                            NormalizedUserName = "EDUARDORIBEIRO",
                            PasswordHash = "AQAAAAIAAYagAAAAEOoLkKyLhSDhFWowmdkbukdkWxpnMlpRLPgXmYWM04LBn99GkokBGpwrNUZn3GMEXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c0490f2c-f55f-4aee-9204-be990f02731f",
                            TwoFactorEnabled = false,
                            UserName = "EduardoRibeiro"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ninexhype.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ninexhype.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninexhype.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ninexhype.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ninexhype.Models.Categoria", b =>
                {
                    b.HasOne("ninexhype.Models.TipoRoupa", "TipoRoupa")
                        .WithMany("Categorias")
                        .HasForeignKey("TipoRoupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoRoupa");
                });

            modelBuilder.Entity("ninexhype.Models.Produto", b =>
                {
                    b.HasOne("ninexhype.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ninexhype.Models.ProdutoFoto", b =>
                {
                    b.HasOne("ninexhype.Models.Produto", "Produto")
                        .WithMany("Fotos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ninexhype.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ninexhype.Models.Produto", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("ninexhype.Models.TipoRoupa", b =>
                {
                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
